apiVersion: v1
kind: Secret
metadata:
  name: ecom-secret
  # namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secret.MONGO_URI | quote }}
  PORT: {{ .Values.secret.PORT | quote }}
  CLOUDINARY_CLOUD_NAME: {{ .Values.secret.CLOUDINARY_CLOUD_NAME | quote }}
  CLOUDINARY_API_KEY: {{ .Values.secret.CLOUDINARY_API_KEY | quote }}
  CLOUDINARY_API_SECRET: {{ .Values.secret.CLOUDINARY_API_SECRET | quote }}
