apiVersion: v1
kind: Service
metadata:
  name: ecom-server
spec:
  type: {{ .Values.server.service.type }}
  selector:
    app: ecom-server
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}