apiVersion: v1
kind: Service
metadata:
  name: ecom-client
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ecom-client
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}