apiVersion: v1
kind: Service
metadata:
  name: ecom-client
  labels:
    {{ include "ecom.labels" . | nindent 4 }}
spec:
  type: {{ .Values.client.service.type }}
  selector:
    app: ecom-client
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
