apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecom-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: chalange.mokchhedul.free.nf
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ecom-server
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecom-client
                port:
                  number: 80
