apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecom-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: mokchhedul.mdmokchhedulislam.page.gd
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecom-client
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ecom-server
                port:
                  number: 5000
