

image:
  pullPolicy: IfNotPresent

client:
  image:
    repository: mokchhedul/ecom-client
    tag: latest
  replicas: 2
  type: ClusterIP
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

server:
  image:
    repository: mokchhedul/ecom-server
    tag: latest
  replicas: 2
  type: ClusterIP
  env:
    PORT: "5000"
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

config:
  NODE_ENV: production

secret:
  MONGO_URI: "mongodb+srv://mokchheduls46:mokchhedul@cluster0.cxqeo.mongodb.net/ecom?appName=Cluster0"
  PORT: "5000"
  CLOUDINARY_CLOUD_NAME: "dn5llg9d2"
  CLOUDINARY_API_KEY: "645463629883328"
  CLOUDINARY_API_SECRET: "cZzuvUFGNwf8Vkc2YtSGquEP5FY"

hpa:
  enabled: true
  min: 2
  max: 5
  cpu: 70

ingress:
  enabled: true
  host: mokchhedulislam.page.gd
