apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom-client
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: client-image=mokchhedul/ecom-client
    argocd-image-updater.argoproj.io/go-image.update-strategy: digest
    argocd-image-updater.argoproj.io/go-image.allow-tags: regexp:^([a-f0-9]{7,40})$
    argocd-image-updater.argoproj.io/go-image.container-name: go-service
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-creds

spec:
  project: ecom-client
  source:
    repoURL: 'https://github.com/mdmokchhedulislam/devops_ecom_project.git'
    targetRevision: main
    path: k8s/client-helm
  destination:
    namespace: default
    client: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true          
      - ApplyOutOfSyncOnly=true