apiVersion: v1
kind: Service
metadata:
  name: ecom-client
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "ecom.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: ecom-client
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
