image:
  pullPolicy: IfNotPresent

server:
  image:
    repository: mokchhedul/ecom-server
    tag: a43181e523fd0cde464cfe4cdbbd122e5da54596
  replicas: 2
  service:
    type: ClusterIP
    port: 5000
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

config:
  NODE_ENV: production

secret:
  MONGO_URI: "mongodb+srv://mokchheduls46:mokchhedul@cluster0.cxqeo.mongodb.net/ecom?appName=Cluster0"
  PORT: "5000"
  CLOUDINARY_CLOUD_NAME: "dn5llg9d2"
  CLOUDINARY_API_KEY: "645463629883328"
  CLOUDINARY_API_SECRET: "cZzuvUFGNwf8Vkc2YtSGquEP5FY"

hpa:
  enabled: true
  min: 2
  max: 5
  cpu: 70

ingress:
  enabled: true
  host: mokchhedulislam.page.gd
